package com.nahmed.enums;

public enum ConfigProperties {

    BROWSER, IMPLICIT_WAIT, ENVIRONMENT, URL, USERNAME, PASSWORD,
    OVER_RIDE_REPORTS, PASSED_STEPS_SCREENSHOTS, FAILED_STEPS_SCREENSHOTS,
    SKIPPED_STEPS_SCREENSHOTS;

}
