package com.nahmed.cucumber.enums;

public enum ConfigProperties {

    BROWSER, IMPLICIT_WAIT, ENVIRONMENT, MAX_RETRIES_COUNT, URL, USERNAME, PASSWORD, OVER_RIDE_REPORTS, PASSED_STEPS_SCREENSHOTS, FAILED_STEPS_SCREENSHOTS, SKIPPED_STEPS_SCREENSHOTS,
    RETRY_FAILED_TESTS;

}
